name: Build and Push All Docker Images

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build for'
        required: true
        default: 'linux/amd64'
      

jobs:
  build-and-push-all:
    runs-on: "${{ github.event.inputs.platfrom == 'linux/arm64' && 'macos-latest' || 'ubuntu-latest' }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Docker Builder
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ github.event.inputs.platform }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push All Images
        run: |
          # Find all Dockerfiles
          DOCKER_FILES=$(find -name 'Dockerfile')

          # Loop through changed Dockerfiles
          for FILE in $DOCKER_FILES; do
            # Extract path components
            IMAGE_PATH=$(dirname "$FILE")
            IMAGE_NAME=$(echo "$IMAGE_PATH" | sed 's|./||' | sed 's|/|:|' | tr '/' '-')
            FULL_IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME"

            echo "Building and pushing $FULL_IMAGE_NAME"

            # Build and push the image
            docker buildx build \
              --push \
              --platform "${{ github.event.inputs.platform }}" \
              --tag "$FULL_IMAGE_NAME" \
              --label "org.opencontainers.image.source=https://github.com/rahimi-ali/personal-base-docker-images" \
              --label "org.opencontainers.image.licenses=MIT" \
              "$IMAGE_PATH"

          done
